<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>913e409c-bee0-45ea-adf7-9d8130737c00</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.5.2" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\backend\dotnet\src\WorkApi\WorkApi.csproj" />
    <ProjectReference Include="..\frontend\mvc\WorkMvc\WorkMvc.csproj" />
  </ItemGroup>

</Project>
